### ISSUE TITLE
EPP: Unauthenticated poll requests fail with internal error

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#697]
Some, not all, poll message requests fail with internal error

Request:
<command>\n    <poll op=\"req\"/>\n   <clTRID>5a793b07d50a9</clTRID>\n  </command>

Error:
Feb 6 07:15:21 reg-l-epp EPP[5199]: [reg] [39aaf26d-6a3f-4e23-a939-69ee30f48248] [89.31.139.65] FROM-EPP-RESCUE: undefined method `queued_messages' for nil:NilClass

log:
detailed log in chat

**Comment by artur-beljajev** [comment]
Probably caused by #698

**Comment by artur-beljajev** [comment]
Please confirm #698 fixed it.

**Comment by vohmar** [comment]
problem is still there in the production.

**Comment by artur-beljajev** [comment]
@vohmar Authentication and authorisation check is now in place. Once it is ready for testing, check that other parts where those messages are displayed still works. Perhaps there was a reason why it was turned off.

**Comment by vohmar** [comment]
* the request and response do not appear in epp log (/admin/epp_logs)
* there is now one new request command in the epp_log - authrequired. That cannot be there as it is not request command. According to log it is replied to malformed/incomplete request <?xml version="1.0"?>. 2000 seems more appropriate response here.

**Comment by artur-beljajev** [comment]
I debugged 687 with epptelnet
double login is perfectly handled by mod_epp itself
if you don't login, "poll" is handled in the same way
regarding that authrequired: it is also expected
and documented
https://github.com/mod-epp/mod-epp#epperrorroot
<result code="2002">
      <msg lang="en">You need to login first.</msg>

Is returned for both "login" and "poll" commands when unauthenticated using both "master" and "registry-697" branches.
so actually I can partly revert bfe9ef3c1fe2320282f34eae648bd52535000967
since the original command does not reach Rails app
only "authrequired", as per spec

**Comment by artur-beljajev** [comment]
@vohmar  Improvements from this ticket's branch have been incorporated into #694

**Comment by artur-beljajev** [comment]
Branch `registry-697` can be safely removed.
