### ISSUE TITLE
Upgrade paper_trail

### ISSUE THREAD

**Issue by teadur** [internetee/registry#426]
We are running paper_trail 4.0.0.beta3(released in May 2015) what is pre-release of papertrail 4.x
https://github.com/internetee/registry/blob/master/Gemfile.lock#L3

We should upgrade to atleast 4.x latest stable what is 4.2.0 (released  2016-05-31)

If we want to move to Rails 5 we need to upgrade to atleast 5.x. if possible upgrading to latest would make sense.

I propose we need to figure out what/if upgrading paper_trails brakes and then upgrade it.
https://github.com/airblade/paper_trail/blob/master/CHANGELOG.md

We can brake the issue to smaller issues and do it in 3 steps.
1) Upgrade to 4.x stable
2) Upgrade to 5.x
3) Upgrade to 6.x

**Comment by artur-beljajev** [comment]
9.2.0

- Every new version of a domain (at least) gets inserted with a duplicate, since `has_paper_trail` if defined twice:
  - One https://github.com/internetee/registry/blob/cefa37d081f39ae73c500067c56d522841ef9db5/app/models/concerns/versions.rb#L7
  - Two https://github.com/internetee/registry/blob/106592e53e8646b9c075ab1e13d5875d332573e4/app/models/domain.rb#L10
- `DomainStatus` does not have corresponding version class. Kind of a bug, introduced by #756. The correct fix is #945
- `undefined local variable or method `paper_trail_version_class' for #<Class:0x00007f8a87ee19c0>` when tried accessing domain history

**Comment by artur-beljajev** [comment]
I wonder how log_*.session column is used.

(edited)
it seems it's always populated by current time

https://github.com/internetee/registry/blob/78d7d5d894999c4b08e10a00ef5a59ee4093fc69/lib/gem_ext/paper_trail.rb#L20

is there any value other than time in prod?
there is created_at column. I guess session can be dropped
